name: Veracode scan

# This runs only when merged,
# We can add this in manual section
on:
  pull_request:
    types:
      - closed
    branches: 
      - main
      - beta

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash

        run: |
          RANDOM_NUMBER=$(( ( RANDOM % 10 )  + 1 ))
          echo "::set-output name=branch::$(echo ${GITHUB_BASE_REF}_${RANDOM_NUMBER} )"
        id: extract_branch

        
      - name: Generate scan zip
        run: zip targetUpload.zip `find ./ -name "*.js" -o -name "*.json" -o -name "*.ts"`
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'mix-cli'
          createprofile: true
          createsandbox: 'true'
          sandboxname: ${{ format('CI_Sandbox_{0}', steps.extract_branch.outputs.branch) }}
          filepath: 'targetUpload.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          criticality: 'Low'
          deleteIncompleteScan: true
